language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ant check

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
